config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :cameras do
    resources :bookings do
      member do
        patch :accept
        patch :decline
      end
    end
  end

  # resources :dashboard do
  #   resources :cameras
  # end

  get "/dashboard", to: "pages#dashboard"
  # get "/cameras/dashboard", to: "pages#dashboard"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :camera
end

app/models/camera.rb
class Camera < ApplicationRecord
  belongs_to :user
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  has_many :bookings, dependent: :destroy
  has_one_attached :photo
  # has_many_attached :photos

  validates :brand, presence: true
  validates :camera_type, presence: true
  validates :address, presence: true

  include PgSearch::Model
  pg_search_scope :global_search,
                  against: [ :brand, :camera_type ],
                  associated_against: {
                    user: [ :first_name, :last_name ]
                  },
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :cameras
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.All
  end

  def new
    @camera = Camera.find(params[:camera_id])
    @booking = Booking.new
  end

  def create
    @camera = Camera.find(params[:camera_id])
    @booking = Booking.new(booking_params)
    @booking.camera = @camera
    @booking.user = current_user
    if @booking.save
      redirect_to camera_path(@camera)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy

    redirect_to camera_path(@booking.camera), status: :see_other
  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.update!({status: "Accepted"})
    redirect_to dashboard_path
  end

    #if user clicks on "accept" button then change status to "accepted"
    #else change to status "available"

  def decline
      @booking = Booking.find(params[:id])
      @booking.update!({status: "Rejected"})
      redirect_to dashboard_path
    end


  # def edit
  #     @booking = Booking.find(params[:id])
  # end

  # def update
  #   @booking = Booking.find(params[:id])
  #   if @booking.update(booking_params)
  #     redirect_to booking_path
  #   else
  #     render :edit, status: :unprocessable_entity
  #   end
  # end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :vehicle_id)
  end
end

app/controllers/cameras_controller.rb
class CamerasController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    if params[:query].present?
      @cameras = Camera.global_search(params[:query]).geocoded
    else
      @cameras = Camera.geocoded
      @markers = @cameras.map do |camera|
        {
          lat: camera.latitude,
          lng: camera.longitude,
          info_window_html: render_to_string(partial: "info_window", locals: {camera: camera}),
          marker_html: render_to_string(partial: "marker")
        }
      end
    end
  end

  def show
    @camera = Camera.find(params[:id])
  end

  def new
    @camera = Camera.new
  end

  def create
    @camera = Camera.new(camera_params)
    @camera.user = current_user
    # @photo = Camera.photo.find(params[:id])

    if @camera.save
      redirect_to camera_path(@camera)

    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @camera = Camera.find(params[:id])
  end

  def update
    @camera = Camera.find(params[:id])
    if @camera.update(camera_params)
      redirect_to camera_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @camera = Camera.find(params[:id])
    @camera.destroy
    redirect_to cameras_path, status: :see_other
  end

  private

  def camera_params
    params.require(:camera).permit(:brand, :camera_type, :address, :user_id, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    redirect_to cameras_path if user_signed_in?
  end

  def dashboard
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/edit.html.erb
<h1>Bookings#edit</h1>
<p>Find me in app/views/bookings/edit.html.erb</p>

app/views/bookings/index.html.erb
<h1>Bookings#index</h1>
<p>Find me in app/views/bookings/index.html.erb</p>

app/views/bookings/new.html.erb
<h1>Book your item</h1>
<%= simple_form_for [@camera, @booking] do |form| %>
<div class="form-inputs">
    <%= form.input :start_date %>
    <%= form.input :end_date %>
</div>
    <%= form.submit 'Confirm booking', class: "btn btn-primary btn-sm text-white" %>
<% end %>

app/views/bookings/show.html.erb
<h1>Bookings#show</h1>
<p>Find me in app/views/bookings/show.html.erb</p>

app/views/cameras/_form-book-new.html.erb
<%# form with book button, starting date and ending date %>

app/views/cameras/_form-edit.html.erb
<%= simple_form_for(@camera) do |form| %>

  <div class="form-inputs">
    <%= form.input :brand, collection: %w[Nikon Canon Sony Olympus Leica Polaroid Instax], prompt: "Choose the brand of your camera"%>
    <%= form.input :camera_type, collection: %w[DSL Mirrorless Compact Film Instant], prompt: "Choose the type of camera" %>
    <%= form.input :address,
    input_html: {data: {address_autocomplete_target: "address"}},
    wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}, class:"d-none"}%>

  </div>

  <div class="form-actions">
    <%= form.button :submit, 'Update your camera', :class => "btn btn-primary text-white btn-sm"%>  <%= link_to "> Back to listings", cameras_path, :class => "btn btn-dark text-white btn-sm"  %>
  </div>
<% end %>
</div>

app/views/cameras/_form-new.html.erb
<%= simple_form_for(@camera) do |form| %>

  <div class="form-inputs">
    <%= form.input :brand, collection: %w[Nikon Canon Sony Olympus Leica Polaroid Instax], prompt: "Choose the brand of your camera"%>
    <%= form.input :camera_type, collection: %w[DSL Mirrorless Compact Film Instant], prompt: "Choose the type of camera" %>
    <%= form.input :address,
    input_html: {data: {address_autocomplete_target: "address"}},
    wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}%>
    <%= form.input :photo, as: :file %>

  </div>

  <div class="form-actions mt-4">
    <%= form.button :submit, '^ Upload your camera', :class => "btn btn-sm form-btn-new" %> <%= link_to "> Back to listings", cameras_path, :class => "btn btn-outline-light btn-sm form-btn-back" %>
  </div>
<% end %>

app/views/cameras/_info_window.html.erb
<h2><%= camera.camera_type %></h2>
<p><%= camera.address %></p>

app/views/cameras/_marker.html.erb
<%= image_tag "logo.png", height: 30, width: 30, alt: "Logo" %>

app/views/cameras/dashboard.html.erb
<h1>Cameras#dashboard</h1>
<p>Find me in app/views/cameras/dashboard.html.erb</p>

app/views/cameras/edit.html.erb
<br>
<br>
<div class="container">
  <h1>Edit the settings of your <%= @camera.brand %></h1>
  <p>Here we will have a <strong>form where we can change the camera info</strong></p>

  <div><%= render "form-edit", camera: @camera %>
  
</div>

app/views/cameras/index.html.erb
<div class="container mt-4">
<!--<div class="row justify-content-left">
  <div class="col-sm-12 my-3">
    <%= form_with url: cameras_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Type a keyword"
        %>
      <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>-->
  <h1><strong>Choose a camera!</strong></h1>
  <p>We have all this available shares:</p>
  <hr>
  <div class="d-flex justify-content-between">
    <% if @cameras.any? %>
      <div class="row">
        <% @cameras.each do |camera| %>
        <div class="col-3 mb-4">
          <div class="card border-0" style="width: 19.5rem;">
            <% if camera.photo.present? %>
              <%= cl_image_tag camera.photo.key, crop: :fill, class: "card-img-top", style: "height:250px; object-fit:cover; border-radius: 30px 30px 0px 0px;" %>
            <% else %>
              <img class="card-img-top " style="border-radius: 30px 30px 0px 0px;" src="height:250px; object-fit:cover; https://d39l2hkdp2esp1.cloudfront.net/img/photo/35737/35737_00_2x.jpg" alt="Card image cap">
            <% end %>
          <div class="card-box text-white">
            <h4><%= link_to camera.brand, camera, class: "text-decoration-none text-white"%></h4>
            <p><%= camera.camera_type %></p>
            <h5><%= camera.address %></h5>
            <p><%= camera.user.first_name %> <%= camera.user.last_name %></p>
          </div>
        </div>
      </div>
    <% end %>
    <% else %>
      <em>Sorry, no cameras found.</em>
    <% end %>
    </div>
  </div>

  <h1><strong>Search a camera near you</strong></h1>
  <p>Type a location</p>
   <hr>
  <div id="map" style="width: 100%; height: 600px;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>


<!--<%= image_tag "https://i.pinimg.com/1200x/40/c1/d8/40c1d8caa349faa3aa1c65f5916f146c.jpg", class: "avatar-med" %>
-->

app/views/cameras/new.html.erb
<div class="container mx-auto w-50 mt-0 text-white bg-dark mb-3 px-5 py-5 rounded" style="max-width: 50rem;">
  <h1>Upload your new camera</h1>
  <p>Please define <strong>type of camera, brand, pickup address</strong> and upload a good quality <strong>image of your camera.</strong></p>

  <div><%= render "form-new", camera: @camera %></div>

</div>

app/views/cameras/show.html.erb
<div class="container d-flex justify-content-center mt-5">

  <div id="big pic" >
  <%= cl_image_tag @camera.photo.key, height: 450, width: 700, crop: :fill, class: "cam-pic" %>
  </div>

  <div id="cam specs" class="cam-card px-5 py-5" style="border-radius: 0px 40px 40px 0px;">

    <div class="d-flex align"><%= link_to "< Book me!", new_camera_booking_path(camera_id: @camera.id, booking_id: @booking_id), :class => "btn btn-light btn-lg btn-book" %>
    </div>

    <h1 class="mt-5" style="font-family: 'Amaranth', sans-serif;"><%= @camera.brand %> <%= @camera.camera_type %> camera </h1>

    <h5>brand: <%= @camera.brand %> | type: <%= @camera.camera_type %></h5>
    <h5>address: <%= @camera.address %></h5>
    <h5 class="mb-5">owner: <%= @camera.user.first_name %> <%= @camera.user.last_name %></h6>

    <div class="d-flex align-items-end">
      <%= link_to "> Back to listings", cameras_path, :class => "btn btn-dark btn-bar text-white btn-sm mx-1" %>
      <%= link_to "Edit camera", edit_camera_path(@camera), class: "btn btn-primary btn-bar text-white btn-sm mx-1" %>
      <%= link_to "x Delete camera",
        camera_path(@camera),
        data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
        class: "btn btn-danger btn-bar text-white btn-sm mx-1" %>

    </div>

  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photorent</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Amaranth:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">

    <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v5.0.0/mapbox-gl-geocoder.css" type="text/css">

    <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v5.0.0/mapbox-gl-geocoder.css" type="text/css">

  </head>

  <body style="background-color: #f1faee">
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/flashes" %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container mt-4 mx-auto w-75 ">
  <h5><strong>Dashboard</strong></h5>
  <hr>
  <h2 class="mt-5" style="font-family: 'Amaranth', sans-serif;">My Cameras</h2>
  <hr>
  <p><%= image_tag "https://i.pinimg.com/1200x/40/c1/d8/40c1d8caa349faa3aa1c65f5916f146c.jpg", class: "avatar mx-1" %>  <%= current_user.first_name if user_signed_in?%>'s <mark>owned</mark> cameras </p>
  <hr>

  <ul class="list-group">
  <% current_user.cameras.each do |camera|%>

  <%# <%= link_to camera.camera_type + " | " + camera.brand + " | "%>

      <li class="list-group-item list-group-item-light d-flex justify-content-between">
        <div class="d-flex align-items-center">
        <%= link_to camera.brand, camera, class: "font-weight-bold text-dark h6 text-decoration-none align-middle mb-0 mx-1" %>
         📷 | <%= camera.camera_type%></div>
        <div class="d-flex align-items-center"><% camera.bookings.where(status: "Pending").each do |booking|%>
        state: <strong><%=booking.status%></strong>
        <%=button_to "Approve", accept_camera_booking_path(:camera_id => booking.camera, :id => booking), method: :patch, class: "btn dash-btn-accept btn-sm" %>
        <%=button_to "Reject", decline_camera_booking_path(:camera_id => booking.camera, :id => booking), method: :patch, class: "btn dash-btn-reject btn-sm" %>
<!--        <%=link_to "Delete", dashboard_path(:camera_id => booking.camera, :id => booking), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn dash-btn-delete btn-sm" %>
-->
        <% end %>
        </div>
      <% end %>
      </li>

  </ul>

<hr>
<div><%=link_to "+ Add new camera", new_camera_path, class: "btn dash-btn-new-cam" %>
</div>

  <h2 class="mt-5" style="font-family: 'Amaranth', sans-serif;">My Bookings</h2>
  <hr>
  <p><%= current_user.first_name if user_signed_in?%>'s <mark>rented</mark> cameras </p>
  <hr>

  <ul class="list-group mb-5">
      <% current_user.bookings.each do |booking|%>

      <li class="list-group-item list-group-item-light d-flex justify-content-between" style="height: 45px;">
      <div >
      <strong><%= booking.camera.brand %></strong>
      <%= booking.camera.camera_type %>
      </div>

      <div><%= "Start Date: " + booking.start_date.to_s + " | " + "End Date: " + booking.end_date.to_s + " | "%><strong><%= booking.status %></strong><%= " by " + booking.camera.user.first_name %>

    </div>
    </li>
      <% end %>

  </ul>
</div>

app/views/pages/home.html.erb
<!-- <%= cl_image_tag("ilu_landing_page2_ycy9dv",
      width: 400, height: 300, crop: :fill) %> -->

<div>
  <%= image_tag "https://res.cloudinary.com/div6oduuz/image/upload/v1692925270/ilu_landing_page2_ycy9dv.png", class: "ilu_landing_page", alt: "people sharing cameras" %>
  <div class="centered">

  <h1><i class="fa-solid fa-heart fa-beat-fade fa-xs" style="color: #e63946;"></i> Own a million Cameras.</h1>
  <h1>without spending a single penny.</h1>
  <br>
  <h4>Lend and borrow cameras. Earn pixelKarma.</h4>
  <br>
  <p>Please <%= link_to "Sign up", new_user_registration_path%> or <%= link_to "Log in", user_session_path%> to see the best cameras in town.</p>

  </div>
</div>

<%# <%= user_signed_in? %>
<%# <%= current_user.name %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div id="our-logo">

  <%= link_to "CamShare", cameras_path, :class => "navbar-brand"%>


  </div>

  <%# <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
  </button> %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto">
      <% if user_signed_in? %>
        <div>
          <%= form_with url: cameras_path, method: :get, class: "navbar-search d-flex" do %>
            <%= text_field_tag :query,
                  params[:query],
                  class: "form-control mx-2",
                  placeholder: "Find the perfect gear for you"
              %>
            <%= submit_tag "Search", name: "", class: "btn btn-secondary btn-sm navbar-search-btn" %>
        </div>
      <% end %>

      <div><%= link_to "Dashboard", dashboard_path, class: "btn btn-light btn-sm navbar-btn text-decoration-none" %></div>

      <div><%= link_to "Add listing", new_camera_path, class: "btn btn-light btn-sm navbar-btn text-decoration-none"%></div>

      <li class="nav-item dropdown" align:>

        <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= image_tag "https://avatars.githubusercontent.com/u/21160316?v=4", class: "avatar", alt: "dropdown menu" %>
        </a>

        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
          <%= link_to "Profile page", "#", class: "dropdown-item" %>
          <%= link_to "Dashboard", "#", class: "dropdown-item" %>
          <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
        </div>
      </li>

    <% else %>
      <li><%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %></li>
      <li><strong><%= link_to "Login", new_user_session_path, class: "nav-link" %></strong></li>
    <% end %>

    </ul>

  </div>
</div>
<div ><%= image_tag "https://res.cloudinary.com/div6oduuz/image/upload/v1692926253/color_bar_q5tl2g.png", class: "nav-color-bar", style: "width: 135px; margin-top: -12px; margin-left: 50px;", alt: "people sharing cameras" %>
</div>
<!-- <div class="container mt-3">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="#">Library</a></li>
            <li class="breadcrumb-item active" aria-current="page">Data</li>
          </ol>
</div>-->